#%RAML 1.0 NamedExample


value:
   -
     ID: 1
     Title: "This is my first note"
     Content: "Be happy"
     CreatedAt: 2021/04/01
     UpdatedAt: 2021/04/01

   -
     ID: 2
     Title: "This is my second note"
     Content: "Craft soft is always the best"
     CreatedAt: 2021/05/01
     UpdatedAt: 2021/05/01