#%RAML 1.0 NamedExample
[
  {
    "empID": 1,
    "empName": "Nebiha",
    "empAge": 28,
    "empSaalry": 12000,
    "empAddress": "MD"
  },
    {
    "empID": 2,
    "empName": "Abu",
    "empAge": 30,
    "empSaalry": 14000,
    "empAddress": "DC"
  },
    {
    "empID": 3,
    "empName": "Frew",
    "empAge": 27,
    "empSaalry": 11000,
    "empAddress": "VA"
  },
    {
    "empID": 4,
    "empName": "Soressa",
    "empAge": 31,
    "empSaalry": 15000,
    "empAddress": "MD"
  },
    {
    "empID": 5,
    "empName": "Hanan",
    "empAge": 20,
    "empSaalry": 9000,
    "empAddress": "OH"
  }
]