#%RAML 1.0 NamedExample
        {
        "productid": 113,
        "categoryid":12, "name":"Google Home",
        "description":"Google home lets you automate stuff. It's cool.",
        "video_url":"https://www.youtube.com/embed/r0iLfAV0pIg",
        "price":6000
        }