#%RAML 1.0 NamedExample
[{
                username: "john",
                fname: "Johson",
                lname: "Motosa",
                userid: 2323,
                orderid: 4323,
                email: "john@example.com"
              },
               {
                username: "sara",
                fname: "Sara",
                lname: "Sanni",
                userid: 5555,
                orderid: 9999,
                email: "sara@example.com"
              }]