#%RAML 1.0 DataType

type: object
properties:
  username: string
  fname: string
  lname: string
  userid: integer
  orderid: integer
  email: string

#  username: "john",
#                 fname: "Johson",
#                 lname: "Motosa",
#                 userid: 2323,
#                 orderid: 4323,
#                 email: "john@example.com"